1.select mamh, tenmh, donvitinh, dongia from mathang
2.select mamh, tenmh, donvitinh, dongia from mathang where dongia>=62
3.select nhacungcap.mancc, nhacungcap.tenncc, mathang.mamh, mathang.tenmh, mathang.donvitinh, mathang.dongia from nhacungcap inner join mathang on nhacungcap.mancc=mathang.mancc where nhacungcap.mancc=2 or nhacungcap.mancc=4
4.select nhacungcap.mancc, nhacungcap.diachi, nhacungcap.tenncc, mathang.mamh, mathang.tenmh, mathang.donvitinh, mathang.dongia from nhacungcap inner join mathang on nhacungcap.mancc=mathang.mancc where nhacungcap.diachi='TP.HCM'
5.select dondathang.maddh, dondathang.ngaydh, dondathang.makh, khachhang.tenkh, mathang.mamh, mathang.tenmh, chitietddh.soluong from chitietddh inner join mathang on chitietddh.mamh=mathang.mamh inner join dondathang on chitietddh.maddh=dondathang.maddh inner join khachhang on khachhang.makh=dondathang.makh where dondathang.ngaydh between '1997-01-01' and '1997-01-31'
6.select dondathang.maddh, dondathang.ngaydh, dondathang.ngaygiao, dondathang.manv, nhanvien.holot, nhanvien.tennv from dondathang inner join nhanvien on nhanvien.manv=dondathang.manv where month(dondathang.ngaygiao)=2 and year(dondathang.ngaygiao)=1997
7.select dondathang.maddh, dondathang.ngaydh, dondathang.makh, khachhang.tenkh, dondathang.manv, nhanvien.holot, nhanvien.tennv from dondathang inner join khachhang on dondathang.makh=khachhang.makh inner join nhanvien on dondathang.manv=nhanvien.manv where dondathang.ngaygiao<'1997-03-01' and nhanvien.manv=4 or nhanvien.manv=5
8.select manv, holot, tennv, diachinv, ngaynviec, phai from nhanvien where phai='M'
9.select madv, manv, holot, tennv, phai, luongcb, ngaynviec from nhanvien where luongcb<300 and ngaynviec between '1991-07-01' and '1992-11-30'
10.select manv, madv, holot, tennv, phai, luongcb, ngaynviec from nhanvien where (phai='F' and diachinv like '%Q1%') or phai='M'
11.select nhanvien.manv, nhanvien.holot, nhanvien.tennv, nhanvien.madv, donvi.tendv, chamcong.thang, chamcong.nam, chamcong.ngaycong from nhanvien inner join chamcong on nhanvien.manv=chamcong.manv inner join donvi on nhanvien.madv=donvi.madv where chamcong.thang=1 and chamcong.nam=1999 and chamcong.ngaycong<25
12.select dondathang.maddh, dondathang.ngaydh, dondathang.ngaygiao, dondathang.manv, nhanvien.holot, nhanvien.tennv, nhanvien.phai from dondathang inner join nhanvien on dondathang.manv=nhanvien.manv where nhanvien.phai='F'
13.select dondathang.maddh, dondathang.ngaydh, dondathang.ngaygiao, dondathang.makh, khachhang.tenkh, datediff(dondathang.ngaygiao, dondathang.ngaydh) as thoigian from dondathang inner join khachhang on dondathang.makh=khachhang.makh where datediff(dondathang.ngaygiao, dondathang.ngaydh)<=15
14.select dondathang.maddh, dondathang.ngaydh, chitietddh.mamh, mathang.tenmh, chitietddh.soluong, mathang.dongia, chitietddh.soluong * mathang.dongia * (1-chitietddh.giamgia) as thanhtien from dondathang inner join chitietddh on dondathang.maddh=chitietddh.maddh inner join mathang on chitietddh.mamh=mathang.mamh
15.select year(dondathang.ngaydh) as nam, quarter(dondathang.ngaydh) as quy, dondathang.ngaydh, dondathang.maddh, dondathang.makh, khachhang.tenkh, dondathang.manv, nhanvien.tennv from dondathang inner join nhanvien on nhanvien.manv=dondathang.manv inner join khachhang on khachhang.makh=dondathang.makh where year(dondathang.ngaydh)=1997 and quarter(dondathang.ngaydh)=1
16.select chitietddh.maddh, dondathang.ngaydh, mathang.mamh, mathang.tenmh from dondathang inner join chitietddh on dondathang.maddh=chitietddh.maddh inner join mathang on chitietddh.mamh=mathang.mamh where mathang.mamh in (1,3,5,7)
17.select matp, count(*) as soluongkhachhang from khachhang group by matp
18.select count(*) as soluong, madv from nhanvien group by nhanvien.madv
19.select count(*) as tongsoddh, year(dondathang.ngaydh) as nam, dondathang.makh, khachhang.tenkh from dondathang inner join khachhang on khachhang.makh=dondathang.makh group by year(dondathang.ngaydh), dondathang.makh, khachhang.tenkh
20.select year(dondathang.ngaydh) as nam, dondathang.maddh, dondathang.makh, dondathang.ngaydh, dondathang.ngaygiao, sum(chitietddh.soluong * mathang.dongia * (1 - chitietddh.giamgia)) as tongtri from dondathang inner join chitietddh on chitietddh.maddh = dondathang.maddh inner join mathang on chitietddh.mamh = mathang.mamh group by dondathang.maddh, dondathang.makh, dondathang.ngaydh, dondathang.ngaygiao, year(dondathang.ngaydh);
21.select sum(soluong * dongia * (1 - giamgia)) as tongtien, year(dondathang.ngaydh) as nam, dondathang.makh, khachhang.tenkh from chitietddh join dondathang on chitietddh.maddh=dondathang.maddh join khachhang on khachhang.makh=dondathang.makh join mathang on mathang.mamh=chitietddh.mamh group by year(dondathang.ngaydh),khachhang.makh,khachhang.tenkh